### ISSUE TITLE
the question about the gt mask

### ISSUE THREAD

**Issue by yhl1010** [lxtGH/DecoupleSegNets#10]
In dataloder there is only one mask image in gt, but in the paper there are two kinds of seg masks, one is full mask and the other is body mask. so i have a question: What kind of mask is in gt?

**Comment by lxtGH** [comment]
body mask is from original NVIDIA inplementation. 

while binary mask can be founded here. 
https://github.com/lxtGH/DecoupleSegNets/blob/69784691a66a978224075fa933b7dd09c142f9ef/datasets/cityscapes.py#L490
