### ISSUE TITLE
我在实例化模型的时候遇到了这个错“TypeError: 'NoneType' object is not callable”

### ISSUE THREAD

**Issue by Wwwwan** [lxtGH/DecoupleSegNets#12]
你好！
我在将模型的类实例化的时候遇到了错误：在mynn.py 的 Norm2d 函数中 layer = getattr(cfg.MODEL, 'BNFUNC'）这里报了错，显示layer 是 Nonetype。报错信息是：TypeError: 'NoneType' object is not callable。这里应该怎么改呢？

**Comment by lxtGH** [comment]
这个问题应该是bn没有import进来吧？
