### ISSUE TITLE
Why the pre training model is inconsistent and cannot be loaded

### ISSUE THREAD

**Issue by dingzifan** [lxtGH/DecoupleSegNets#2]
/data_1/TEST/deeplabv3_decouple_82.pth
/data_1/TEST/fcn_r50_decouple.pth
/data_1/TEST/psp_r50_decouple_r50.pth
/data_1/TEST/wider_resnet38_best.pth

Error reported all the time:
RuntimeError: =====================Could not load ImageNet weights of WideResNet38 network.=======================

**Comment by lxtGH** [comment]
Hi the pretrained model have released in readme. However, note that we use the Mapillary pretrained model for the final model.  You can use such backbone to do the Mapillary pretraining.

**Comment by dingzifan** [comment]
> Hi the pretrained model have released in readme. However, note that we use the Mapillary pretrained model for the final model. You can use such backbone to do the Mapillary pretraining.

Can I add your wechat?My Wechat:1150888858

**Comment by dingzifan** [comment]
> Hi the pretrained model have released in readme. However, note that we use the Mapillary pretrained model for the final model. You can use such backbone to do the Mapillary pretraining.
Can I add your wechat? My wechat:1150788858

**Comment by dingzifan** [comment]
Can I add your wechat? My wechat:1150788858

**Comment by lxtGH** [comment]
You send me email
