### ISSUE TITLE
Q: Module setting in BG for ablation studies.

### ISSUE THREAD

**Issue by Yonma** [lxtGH/DecoupleSegNets#24]
Hello, Li:

I'm confused in **4.1 Abaltion Studies: Ablation study on the effect of each component:**

I did not find any detailed description either in your paper (both the one in arxiv and the one published), nor in codes of this open-repo. And I can't figure it out myself for the setting variety, did I miss some information on above resources (though I've check them from A to Z servel times) or could you tell me about your settings here?

For example, **removing warping in BG**:

1. If **remove warping part solely**, then the features out from Flow-field has num_channels = 2, while features came from ASPP have num_channels = 256, so it's unable to use subtraction op on them directly.
2.  if **remove both the Flow-field and the wraping part**, then features from concat op (the one after the encoder-decoder part) has num_channels = 512, still improper.

So did you add a new 1*1 conv block after the en-decoder part to getnerate the body part removing both Flow-field and warping? 

As for removing En-decoder part in BG, did you add a 1*1 conv which have num_in_channels = 512 and num_out_channel s= 256?

Thanks in advance **: )**

**Comment by lxtGH** [comment]
Your undertanding is correct. I add extra 1*1 conv blocks for dimension alignment. https://github.com/lxtGH/DecoupleSegNets/blob/87a52cbc2674f006870b14962df9a9c3cd94cf0a/network/deepv3_decouple.py#L68
See this. Just like this line.
