### ISSUE TITLE
How to train my own dataset?

### ISSUE THREAD

**Issue by YBIO** [lxtGH/DecoupleSegNets#3]
Hi, thank you for sharing your great work! I want to train the model on my own dataset (my dataset has 9 classes). Could you please give me  some instructions? Thank u

**Comment by lxtGH** [comment]
@Shang-XH 
Thanks for your attention! 
1, First you should write xxx.py (dataset) and write the get_item function according to your needs.
2, Then you should register your dataset in __init__.py by specifying your transform and loaders. Finaly add your data path in config.py.

I suggest you have a look at bdd.py to see how it works.

**Comment by YBIO** [comment]
> @Shang-XH
> Thanks for your attention!
> 1, First you should write xxx.py (dataset) and write the get_item function according to your needs.
> 2, Then you should register your dataset in **init**.py by specifying your transform and loaders. Finaly add your data path in config.py.
> 
> I suggest you have a look at bdd.py to see how it works.

Thank u for the instruction~I will try it.
