### ISSUE TITLE
About the base pretrained_models

### ISSUE THREAD

**Issue by pingjun18-li** [lxtGH/DecoupleSegNets#4]
Hi, thanks for your great job!
I want run the scripts (sh ./scripts/train/train_cityscapes_ResNet50_deeplab.sh) to train the base model, but I could not find the pretrained_models ("./pretrained_models/resnet50-deep.pth"). Could you share the base models also?
Thank you again.

**Comment by lxtGH** [comment]
Please read the readme.md We have provide the link in baidu drive.
