### ISSUE TITLE
GPU Usage

### ISSUE THREAD

**Issue by chuzcjoe** [lxtGH/DecoupleSegNets#6]
Hi, i noticed that the whole network size is relatively small but when i started training the model, my GPU memory is almost fully loaded even i set the batch size to 4. I was wondering where the most computation and parameters come from. Thanks.

**Comment by lxtGH** [comment]
Hi what is your GPU memory?  It has at least 12GB to run the training process.

**Comment by chuzcjoe** [comment]
> Hi what is your GPU memory?  It has at least 12GB to run the training process.

10GB

**Comment by lxtGH** [comment]
So you can not run this code with such limited GPU memory.
