### ISSUE TITLE
Class Uniform Sampling

### ISSUE THREAD

**Issue by wuyefeilin** [lxtGH/DecoupleSegNets#7]
DecoupleSegNets is excellent. 

In the paper, you said as follow.
We first record the centroid of areas containing the class of interest. 
During training, we take half of the samples from the standard randomly cropped images and the other half from the centroids to make sure the training crops for all classes are approximately uniform per epoch.

I have some confused about class uniform sampling. 
1. Are you record the centroid of areas of per class and per images?
2. does the 'half' mean that half of every batch? 
3.  does 'half from the centroids' mean that have a crop centered around centroids

**Comment by lxtGH** [comment]
Where did you find these words?  

The uniform sampling is inlcuded to balance traning on for rare class like train, truck.  I only use it in CityScapes.

This is not our contribution and you can find more details in orignal paper. 

https://openaccess.thecvf.com/content_CVPR_2019/papers/Zhu_Improving_Semantic_Segmentation_via_Video_Propagation_and_Label_Relaxation_CVPR_2019_paper.pdf
