### ISSUE TITLE
Couldn't find cityscapes_best.pth

### ISSUE THREAD

**Issue by JohnnyZhang728** [lxtGH/DecoupleSegNets#8]
Hello, thank you for sharing your great work!
When I was running _demo_folder_decouple.py_, I couldn't find your pretrained model : **cityscapes_best.pth**.
Could you please share your link with the model **cityscapes_best.pth** to us?

**Comment by lxtGH** [comment]
Please  see the readme file for reference.  I give the model zoo for downloading.
