### ISSUE TITLE
Where is the snapshot saved？

### ISSUE THREAD

**Issue by ZhishengLie** [lxtGH/DecoupleSegNets#9]
When I train a model without the argument of snapshot, how can I evaluate the model ? Because the argument of snapshot must be required.
`parser.add_argument('--snapshot', required=True, type=str, default='')`

Here is the error showed.
`eval.py: error: argument --snapshot: expected one argument`

**Comment by lxtGH** [comment]
--snapshot means the checkpoint dir of trained model. You can find them in the readme links.
